@startuml

component "AC-DC Power Supply" as power
component "DC-DC Converters" as converter
component "AC-AC Converter" as aconverter
component "Cooller Fan" as cooller

database "Solder" as solder {
    component "Thermocouple Solder" as thcSolder
}

database "Heat Gun" as gun {
    component "Thermocouple Heat Gun" as thcHeat
}

node "Main Board" as main {
    component "LCD Display" as display
    component "Microcontroller" as mcu
}

node "Interfaces Board" as interfaces {
    cloud "3/5V DC" as lvdomain {
        component "Encoder Input Temp Solder Iron" as inputTemp
        component "Encoder Input Heat Gun" as inputHeat
        component "Encoder Input Main" as inputMain
    }
    cloud "220V AC" as hvdomain
    cloud "24V AC"  as mvdomain
}

power --> converter : 24/48VDC
power --> hvdomain : 220VAC
power --> aconverter : 220VAC
converter --> main : 3/5V
converter --> cooller : 12V
aconverter --> mvdomain : 24VAC
mvdomain -down-> solder : 24VAC   
hvdomain -down-> gun : 220VAC
main --> lvdomain : 3/5V

thcSolder ..> lvdomain : Temp
thcHeat ..> lvdomain : Temp

lvdomain ...> mcu : Signals
mcu ..> display : UI

lvdomain ..> hvdomain : Ctnrl
lvdomain ..> mvdomain : Cntrl

note right of [aconverter]
  TODO: 
   Find module
   or design PCB
end note


@enduml